import type { UserRole } from '../types';

export const PERMISSIONS = [
  'organizations.read',
  'organizations.update',
  'users.read',
  'users.create',
  'users.update',
  'campuses.read',
  'campuses.manage',
  'classrooms.read',
  'classrooms.manage',
  'students.read',
  'students.create',
  'students.update',
  'students.delete',
  'guardians.read',
  'guardians.manage',
  'attendance.read',
  'attendance.create',
  'student_events.read',
  'student_events.create',
  'buses.read',
  'buses.manage',
  'media.read',
  'media.create',
  'media.delete',
  'notifications.read',
  'notifications.update',
] as const;

export type Permission = (typeof PERMISSIONS)[number];

const ALL: Permission[] = [...PERMISSIONS];

export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  ADMIN: ALL,
  SUPERVISOR: [
    'organizations.read',
    'users.read',
    'users.create',
    'users.update',
    'campuses.read',
    'campuses.manage',
    'classrooms.read',
    'classrooms.manage',
    'students.read',
    'students.create',
    'students.update',
    'students.delete',
    'guardians.read',
    'guardians.manage',
    'attendance.read',
    'attendance.create',
    'student_events.read',
    'student_events.create',
    'buses.read',
    'buses.manage',
    'media.read',
    'media.create',
    'media.delete',
    'notifications.read',
    'notifications.update',
  ],
  TEACHER: [
    'organizations.read',
    'campuses.read',
    'classrooms.read',
    'students.read',
    'guardians.read',
    'attendance.read',
    'attendance.create',
    'student_events.read',
    'student_events.create',
    'media.read',
    'media.create',
    'notifications.read',
    'notifications.update',
  ],
  DRIVER: [
    'organizations.read',
    'campuses.read',
    'students.read',
    'student_events.read',
    'student_events.create',
    'buses.read',
    'notifications.read',
    'notifications.update',
  ],
  GUARDIAN: [
    'organizations.read',
    'students.read',
    'guardians.read',
    'attendance.read',
    'student_events.read',
    'media.read',
    'notifications.read',
    'notifications.update',
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}
